const OK = 200;
const CREATED = 201;

const BAD_REQUEST = 400;
const BAD_AUTORIZATION = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;

module.exports = {
  CREATED,
  OK,
  BAD_REQUEST,
  BAD_AUTORIZATION,
  CONFLICT,
  FORBIDDEN,
  NOT_FOUND,
};
